/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 24 05:31:55 GMT 2024
 */

package org.example.sorting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.sorting.QuickSort;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuickSort_ESTest extends QuickSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[4];
      intArray0[1] = 3442;
      quickSort0.sort(intArray0, 0, 1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QuickSort quickSort0 = new QuickSort();
      // Undeclared exception!
      try { 
        quickSort0.sort((int[]) null, 0, 68);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.sorting.QuickSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[2];
      // Undeclared exception!
      try { 
        quickSort0.sort(intArray0, (-1926), (-608));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -608
         //
         verifyException("org.example.sorting.QuickSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[2];
      quickSort0.sort(intArray0, 0, 0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[39];
      intArray0[8] = 12;
      quickSort0.sort(intArray0, 0, 12);
      assertEquals(39, intArray0.length);
  }
}
