/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 07 10:21:16 GMT 2024
 */

package org.example.searching;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.searching.BinarySearch;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BinarySearch_ESTest extends BinarySearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      int[] intArray0 = new int[1];
      binarySearch0.search(intArray0, 0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      // Undeclared exception!
      try { 
        binarySearch0.search((int[]) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.searching.BinarySearch", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      int[] intArray0 = new int[6];
      binarySearch0.search(intArray0, (-1));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      int[] intArray0 = new int[6];
      binarySearch0.search(intArray0, 0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      int[] intArray0 = new int[6];
      int int0 = binarySearch0.search(intArray0, 2);
      assertEquals((-1), int0);
  }
}
