/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 07 10:21:16 GMT 2024
 */

package org.example.searching;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.searching.LinearSearch;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinearSearch_ESTest extends LinearSearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinearSearch linearSearch0 = new LinearSearch();
      int[] intArray0 = new int[1];
      int int0 = linearSearch0.search(intArray0, 1282);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinearSearch linearSearch0 = new LinearSearch();
      int[] intArray0 = new int[2];
      intArray0[1] = (-818);
      int int0 = linearSearch0.search(intArray0, (-818));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinearSearch linearSearch0 = new LinearSearch();
      // Undeclared exception!
      try { 
        linearSearch0.search((int[]) null, 4537);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.searching.LinearSearch", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinearSearch linearSearch0 = new LinearSearch();
      int[] intArray0 = new int[17];
      int int0 = linearSearch0.search(intArray0, 0);
      assertEquals(0, int0);
  }
}
