/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 07 10:20:15 GMT 2024
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.ExamGrades;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExamGrades_ESTest extends ExamGrades_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(50);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(76);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(86);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(100);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(0);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(70);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(80);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(59);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      // Undeclared exception!
      try { 
        examGrades0.grade(1327);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // invalid points
         //
         verifyException("org.example.ExamGrades", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      int int0 = examGrades0.grade(90);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExamGrades examGrades0 = new ExamGrades();
      // Undeclared exception!
      try { 
        examGrades0.grade((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // invalid points
         //
         verifyException("org.example.ExamGrades", e);
      }
  }
}
