/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 24 05:23:36 GMT 2024
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.WhichPath;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WhichPath_ESTest extends WhichPath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = WhichPath.makeDecision(0, 615, 615);
      assertEquals("Path 8", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = WhichPath.makeDecision(10, 5, 10);
      assertEquals("Path 9", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = WhichPath.makeDecision(1639, (-1428), 10);
      assertEquals("Path 3", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = WhichPath.makeDecision(94, 5, 10);
      assertEquals("Path 5", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = WhichPath.makeDecision(10, 3298, (-2177));
      assertEquals("Path 6", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = WhichPath.makeDecision((-10), 446, (-10));
      assertEquals("Path 7", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = WhichPath.makeDecision(0, 0, 0);
      assertEquals("Path 9", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = WhichPath.makeDecision(3743, 3743, 0);
      assertEquals("Path 5", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = WhichPath.makeDecision(3743, 0, 1);
      assertEquals("Path 2", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = WhichPath.makeDecision(1003, (-652), 1003);
      assertEquals("Path 3", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = WhichPath.makeDecision(3743, 0, 0);
      assertEquals("Path 1", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = WhichPath.makeDecision(1003, 1003, 1003);
      assertEquals("Path 4", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = WhichPath.makeDecision(1003, (-652), (-652));
      assertEquals("Path 3", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      WhichPath whichPath0 = new WhichPath();
  }
}
