/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 07 10:20:51 GMT 2024
 */

package org.example.sorting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.sorting.BubbleSort;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BubbleSort_ESTest extends BubbleSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BubbleSort bubbleSort0 = new BubbleSort();
      Integer[] integerArray0 = new Integer[7];
      Integer integer0 = new Integer((-857));
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[2] = integer0;
      integerArray0[3] = integerArray0[1];
      integerArray0[4] = integerArray0[2];
      integerArray0[5] = integer0;
      integerArray0[6] = integerArray0[1];
      bubbleSort0.sort(integerArray0);
      assertEquals(7, integerArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BubbleSort bubbleSort0 = new BubbleSort();
      Integer[] integerArray0 = new Integer[7];
      // Undeclared exception!
      try { 
        bubbleSort0.sort(integerArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.sorting.BubbleSort", e);
      }
  }
}
